In [ ]:
from __future__ import print_function
import torch

**empty one**

In [ ]:
x = torch.empty(5,3)
x

tensor([[3.3119e-36, 0.0000e+00, 4.2039e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [8.9773e-33, 1.3563e-19, 2.9514e+29],
        [1.2203e-32, 1.3563e-19, 4.5145e+27],
        [1.3556e-19, 3.0359e+26, 1.1721e-19]])

In [ ]:
type(x)

torch.Tensor

In [ ]:
y = torch.empty(3)
y

tensor([3.3119e-36, 0.0000e+00, 5.3249e-44])

**rand one**

In [ ]:
x_rand = torch.rand(5,3)
x_rand

tensor([[0.7890, 0.5498, 0.8079],
        [0.1525, 0.9650, 0.7478],
        [0.5794, 0.1424, 0.4950],
        [0.3859, 0.5901, 0.4010],
        [0.9648, 0.5159, 0.0696]])

**zeros one**

In [ ]:
x_zeros = torch.zeros(5,3, dtype=torch.long)
x_zeros

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

**directly from data**

In [ ]:
x_data = torch.tensor([i**2 for i in range(5)])
x_data

tensor([ 0,  1,  4,  9, 16])

In [ ]:
z = torch.([])
z

tensor([])

**operators**

In [ ]:
new_x = x_rand + x
new_x

tensor([[7.8902e-01, 5.4979e-01, 8.0793e-01],
        [1.5254e-01, 9.6499e-01, 7.4777e-01],
        [5.7941e-01, 1.4239e-01, 2.9514e+29],
        [3.8589e-01, 5.9009e-01, 4.5145e+27],
        [9.6476e-01, 3.0359e+26, 6.9616e-02]])

In [ ]:
foo = torch.tensor([i**2 for i in range(5)])
bar = torch.tensor([i**4 for i in range(5)])
display(foo,bar)

tensor([ 0,  1,  4,  9, 16])

tensor([  0,   1,  16,  81, 256])

In [ ]:
#in-place bar + foo
bar.add_(foo)
bar

#Any operation that mutates a tensor in-place is post-fixed with an _.

tensor([  0,   2,  20,  90, 272])