In [1]:
import torch

In [2]:
torch.__version__

'1.6.0+cu101'

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu" 

In [4]:
my_tensor = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True
)

In [7]:
torch.arange(
    start=0, end=5, step=2
) 

tensor([0, 2, 4])

In [6]:
torch.arange(
    start=0, end=5) 

tensor([0, 1, 2, 3, 4])

In [ ]:
torch.arange(11)

In [9]:
torch.linspace(start=0.1, end=1, steps=10) 

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [43]:
x = torch.arange(
    start=0, end=5, step=2
) 

t = torch.arange(
    start=5, end=10, step=2
) 

In [45]:
%timeit y = x + t

The slowest run took 275.98 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.07 µs per loop


In [46]:
%timeit y = x.add_(t)

The slowest run took 469.74 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.26 µs per loop


In [49]:
m = torch.rand(5,5)
m

tensor([[0.7807, 0.2336, 0.8564, 0.1800, 0.0645],
        [0.9783, 0.9333, 0.5283, 0.0613, 0.6272],
        [0.5813, 0.7514, 0.5999, 0.3992, 0.6454],
        [0.8847, 0.3314, 0.4218, 0.6134, 0.7795],
        [0.8949, 0.7039, 0.5331, 0.1108, 0.5061]])

In [50]:
m.clamp_(min=0.6)

tensor([[0.7807, 0.6000, 0.8564, 0.6000, 0.6000],
        [0.9783, 0.9333, 0.6000, 0.6000, 0.6272],
        [0.6000, 0.7514, 0.6000, 0.6000, 0.6454],
        [0.8847, 0.6000, 0.6000, 0.6134, 0.7795],
        [0.8949, 0.7039, 0.6000, 0.6000, 0.6000]])

In [53]:
p = torch.rand(10,25)
p

tensor([[0.9975, 0.4513, 0.9387, 0.2216, 0.4463, 0.0927, 0.9138, 0.3922, 0.5551,
         0.1136, 0.5828, 0.6347, 0.8145, 0.6720, 0.2951, 0.3788, 0.9431, 0.7329,
         0.9390, 0.8956, 0.4510, 0.8856, 0.4749, 0.7864, 0.0096],
        [0.0236, 0.4165, 0.8399, 0.6424, 0.4806, 0.9758, 0.9965, 0.9026, 0.6327,
         0.9722, 0.9688, 0.3611, 0.4789, 0.4607, 0.2289, 0.6511, 0.0773, 0.9800,
         0.4741, 0.0938, 0.0907, 0.0661, 0.9122, 0.8580, 0.1296],
        [0.2208, 0.8626, 0.6362, 0.3678, 0.3494, 0.3546, 0.0994, 0.2673, 0.7820,
         0.1618, 0.8978, 0.3621, 0.7978, 0.1514, 0.7750, 0.4586, 0.5194, 0.6687,
         0.1003, 0.6278, 0.4303, 0.6780, 0.5524, 0.6161, 0.9562],
        [0.9992, 0.9872, 0.1520, 0.8446, 0.9212, 0.3684, 0.4109, 0.1314, 0.2488,
         0.5029, 0.6111, 0.9466, 0.5188, 0.7287, 0.7468, 0.5620, 0.8053, 0.0737,
         0.3708, 0.0446, 0.9322, 0.6194, 0.7732, 0.4407, 0.7904],
        [0.1115, 0.7025, 0.7922, 0.7462, 0.4393, 0.8017, 0.1012, 0.3919, 0.5167,
       

In [54]:
p[:,0]

tensor([0.9975, 0.0236, 0.2208, 0.9992, 0.1115, 0.2518, 0.0666, 0.0626, 0.4432,
        0.1417])

In [55]:
p[0,:]

tensor([0.9975, 0.4513, 0.9387, 0.2216, 0.4463, 0.0927, 0.9138, 0.3922, 0.5551,
        0.1136, 0.5828, 0.6347, 0.8145, 0.6720, 0.2951, 0.3788, 0.9431, 0.7329,
        0.9390, 0.8956, 0.4510, 0.8856, 0.4749, 0.7864, 0.0096])

In [68]:
#reshaping
g = torch.arange(16)
g_4x4 = g.view(4,4)
display(g,g_4x4)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [69]:
g_4x4.shape

torch.Size([4, 4])

In [70]:
#transposing
g_4x4.t()

tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])

In [74]:
#cat
h = torch.arange(16)
torch.cat((g,h), dim=0), torch.cat((g,h), dim=0).shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  0,  1,
          2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 torch.Size([32]))

In [78]:
torch.cat((g_4x4,g_4x4), dim=0), torch.cat((g_4x4,g_4x4), dim=0).shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]), torch.Size([8, 4]))

In [79]:
torch.cat((g_4x4,g_4x4), dim=1), torch.cat((g_4x4,g_4x4), dim=1).shape

(tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
         [ 4,  5,  6,  7,  4,  5,  6,  7],
         [ 8,  9, 10, 11,  8,  9, 10, 11],
         [12, 13, 14, 15, 12, 13, 14, 15]]), torch.Size([4, 8]))

**.view(-1)**

In [84]:
#example 1
z = torch.rand(2,5)
z, z.shape

(tensor([[0.5262, 0.1559, 0.2659, 0.0345, 0.2846],
         [0.0609, 0.4717, 0.1036, 0.5935, 0.4798]]), torch.Size([2, 5]))

In [83]:
z.view(-1), z.view(-1).shape

(tensor([0.9037, 0.0071, 0.5688, 0.9799, 0.3975, 0.7288, 0.6553, 0.1237, 0.5349,
         0.7215]), torch.Size([10]))

In [86]:
#example 2
batch = 64
r = torch.rand(batch, 2, 5)

In [89]:
r.view(-1)[:15] #squezing all dimensions into one

tensor([0.1961, 0.0538, 0.9380, 0.0438, 0.5737, 0.8180, 0.1725, 0.7969, 0.4531,
        0.8746, 0.5595, 0.1797, 0.8964, 0.5974, 0.0431])

In [90]:
r.view(batch, -1)[:15] #squezing all dimensions BUT THE FIRST ONE

tensor([[0.1961, 0.0538, 0.9380, 0.0438, 0.5737, 0.8180, 0.1725, 0.7969, 0.4531,
         0.8746],
        [0.5595, 0.1797, 0.8964, 0.5974, 0.0431, 0.4697, 0.8456, 0.3010, 0.2411,
         0.3521],
        [0.1709, 0.8058, 0.7429, 0.2759, 0.3005, 0.2221, 0.5262, 0.1565, 0.2865,
         0.4456],
        [0.3370, 0.6311, 0.9589, 0.0976, 0.9617, 0.9553, 0.5838, 0.8040, 0.0727,
         0.6515],
        [0.9103, 0.7744, 0.4789, 0.0942, 0.8348, 0.0238, 0.7141, 0.0031, 0.9146,
         0.7944],
        [0.4675, 0.9520, 0.4762, 0.4343, 0.0246, 0.1415, 0.0220, 0.4200, 0.6174,
         0.0774],
        [0.5393, 0.1087, 0.2149, 0.5553, 0.1501, 0.9440, 0.5860, 0.7761, 0.7429,
         0.5524],
        [0.3758, 0.6571, 0.9962, 0.0030, 0.7686, 0.3632, 0.5075, 0.7652, 0.4465,
         0.5525],
        [0.1348, 0.7830, 0.3349, 0.7700, 0.2068, 0.1775, 0.6746, 0.3636, 0.0506,
         0.2310],
        [0.4706, 0.4810, 0.4995, 0.9286, 0.3761, 0.3134, 0.1620, 0.9817, 0.3843,
         0.4808],
        [0

**.unsqueeze()**

In [93]:
f = torch.arange(16)
f, f.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 torch.Size([16]))

In [98]:
f.unsqueeze(0), f.unsqueeze(0).shape

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]),
 torch.Size([1, 16]))

In [96]:
f.unsqueeze(1), f.unsqueeze(1).shape

(tensor([[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12],
         [13],
         [14],
         [15]]), torch.Size([16, 1]))